#!/usr/bin/env python

from getpass import getpass

from fmi import FMI


def main():
    fmi = FMI(
        raw_input('Username (e.g. username@me.com): '),
        getpass()
        )

    print('Logging in...')
    fmi.login()
        
    # fetch last positions
    print('Fetching devices...')
    devices = fmi.devices()

    for device in devices['content']:
        print device['name'], '-',
        if not device['location']:
            print 'No location found'
            continue
        print device['location']['longitude'],
        print device['location']['latitude']

if __name__ == '__main__':
    main()

